version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies"
      - node -v
      - npm -v
      - npm ci

  pre_build:
    commands:
      - echo "BUILD_MODE=${BUILD_MODE:-all}"
      - echo "SITE_ID=$SITE_ID"
      - echo "CONCURRENCY=${CONCURRENCY:-2}"
